services:

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d:ro
    ports:
      - 27017:27017

  api:
    build:
      context: ./backend
    environment:
      PORT: 3000
      MONGO_URI: mongodb://database:27017
      DB_NAME: electrolibrary
    ports:
      - 3000:3000
    depends_on:
      - database

volumes:
  mongo-data:
